spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: 12345678
# Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true
sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql
　　zipkin启动类